# Name of the workflow
name: Hello world workflow

#Events that trigger this workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, staging]         # branches change

# Jobs to run 
jobs:
  greet:
  # The type of run to use e.g windows,ubuntu,mac
    runs-on: ubuntu-latest
  # Steps to excute in this job
    steps:
    # Run asingle line command
     - name: Hello
       run: echo "Hello World!" 